// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/log"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameFormViewField = "form_view_field"

// FormViewField mapped from table <form_view_field>
type FormViewField struct {
	FormViewFieldID     uint64                `gorm:"column:form_view_field_id;primaryKey;comment:列雪花id" json:"form_view_field_id"` // 列雪花id
	ID                  string                `gorm:"column:id;not null;comment:列uuid" json:"id"`                                   // 列uuid
	FormViewID          string                `gorm:"column:form_view_id;not null;comment:逻辑视图uuid" json:"form_view_id"`            // 逻辑视图uuid
	TechnicalName       string                `gorm:"column:technical_name;not null;comment:列技术名称" json:"technical_name"`           // 列技术名称
	BusinessName        string                `gorm:"column:business_name;comment:列业务名称" json:"business_name"`                      // 列业务名称
	OriginalName        string                `gorm:"column:original_name;comment:原始字段名称" json:"original_name"`                     // 原始字段名称
	Comment             sql.NullString        `gorm:"column:comment;comment:列备注" json:"comment"`                                    // 列注释
	Status              int32                 `gorm:"column:status;not null;comment:列视图状态(扫描结果) 0：无变化、1：新增、2：删除" json:"status"`     // 列视图状态(扫描结果) 0：无变化、1：新增、2：删除
	PrimaryKey          sql.NullBool          `gorm:"column:primary_key;not null;comment:是否主键" json:"primary_key"`                  // 是否主键
	DataType            string                `gorm:"column:data_type;not null;comment:数据类型" json:"data_type"`                      // 数据类型
	DataLength          int32                 `gorm:"column:data_length;not null;comment:数据长度" json:"data_length"`                  // 数据长度
	DataAccuracy        sql.NullInt32         `gorm:"column:data_accuracy;not null;comment:数据精度（仅DECIMAL类型）" json:"data_accuracy"`  // 数据精度（仅DECIMAL类型）
	OriginalDataType    string                `gorm:"column:original_data_type;not null;comment:原始数据类型" json:"original_data_type"`  // 原始数据类型
	IsNullable          string                `gorm:"column:is_nullable;not null;comment:是否为空" json:"is_nullable"`                  // 是否为空
	DeletedAt           soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`
	StandardCode        sql.NullString        `gorm:"column:standard_code;comment:数据标准code" json:"standard_code"`                 // 关联数据标准code
	StandardName        sql.NullString        `gorm:"column:standard;comment:数据标准名称" json:"standard"`                             // 数据标准名称
	CodeTableID         sql.NullString        `gorm:"column:code_table_id;comment:关联码表ID" json:"code_table_id"`                   // 关联码表ID
	BusinessTimestamp   bool                  `gorm:"column:business_timestamp;comment:是否业务时间字段" json:"business_timestamp"`       // 是否业务时间字段
	SubjectID           *string               `gorm:"column:subject_id" json:"subject_id"`                                        // 关联逻辑实体属性ID（L5）
	ClassifyType        *int                  `gorm:"column:classify_type" json:"classify_type"`                                  // 数据分类方式 1：auto（自动分类） 2：manual（人工分类）
	MatchScore          *string               `gorm:"column:match_score" json:"match_score"`                                      // 关联逻辑实体属性匹配度评分(满分100分)，加%可直接作为匹配度百分比展示
	ResetBeforeDataType sql.NullString        `gorm:"column:reset_before_data_type;comment:重置数据类型" json:"reset_before_data_type"` // 重置前数据类型
	ResetConvertRules   sql.NullString        `gorm:"column:reset_convert_rules"  json:"reset_convert_rules"`                     // 重置转换规则 （仅日期类型）
	ResetDataLength     sql.NullInt32         `gorm:"column:reset_data_length" json:"reset_data_length"`                          // 重置数据长度（仅DECIMAL类型）
	ResetDataAccuracy   sql.NullInt32         `gorm:"column:reset_data_accuracy" json:"reset_data_accuracy"`                      // 重置数据精度（仅DECIMAL类型）
	Index               int                   `gorm:"column:index" json:"index"`                                                  // 字段顺序
	GradeID             sql.NullInt64         `gorm:"column:grade_id" json:"grade_id"`                                            // 分级标签id
	GradeType           sql.NullInt32         `gorm:"column:grade_type" json:"grade_type"`                                        // 数据分级标签获得方式 1：auto（自动匹配分级） 2：manual（人工选择分级）
	SharedType          int32                 `gorm:"column:shared_type;comment:共享属性" json:"shared_type"`                         // 共享属性
	OpenType            int32                 `gorm:"column:open_type;comment:开放属性" json:"open_type"`                             // 开放属性
	SensitiveType       int32                 `gorm:"column:sensitive_type;comment:敏感属性" json:"sensitive_type"`                   // 敏感属性
	SecretType          int32                 `gorm:"column:secret_type;comment:涉密属性" json:"secret_type"`                         // 涉密属性
}

// TableName FormViewField's table name
func (*FormViewField) TableName() string {
	return TableNameFormViewField
}

func (d *FormViewField) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.FormViewFieldID == 0 {
		if d.FormViewFieldID, err = utilities.GetUniqueID(); err != nil {
			log.Errorf("failed to general unique id, err: %v", err)
			return err
		}
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	return err
}

func (d *FormViewField) UniqueKey() string {
	return "id"
}
