// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	utilities "github.com/kweaver-ai/idrm-go-frame/core/utils"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

const TableNameFormView = "form_view"

// FormView mapped from table <form_view>
type FormView struct {
	FormViewID         uint64 `gorm:"column:form_view_id;primaryKey;comment:逻辑视图雪花id" json:"form_view_id"`              // 逻辑视图雪花id
	ID                 string `gorm:"column:id;not null;comment:逻辑视图uuid" json:"id"`                                    // 逻辑视图uuid
	UniformCatalogCode string `gorm:"column:uniform_catalog_code;not null;comment:统一编目的编码" json:"uniform_catalog_code"` // 统一编目的编码
	TechnicalName      string `gorm:"column:technical_name;not null;comment:表技术名称" json:"technical_name"`               // 表技术名称
	BusinessName       string `gorm:"column:business_name;comment:表业务名称" json:"business_name"`                          // 表业务名称
	OriginalName       string `gorm:"column:original_name;comment:原始表名称" json:"original_name"`                          // 原始表名称
	Type               int32  `gorm:"column:type;not null;comment:逻辑视图类型 1：元数据视图、2：自定义视图、3：逻辑实体视图" json:"type"`         // 逻辑视图类型 1：元数据视图、2：自定义视图、3：逻辑实体视图
	DatasourceID       string `gorm:"column:datasource_id;comment:数据源id" json:"datasource_id"`                          // 数据源id
	//TaskID        sql.NullString        `gorm:"column:task_id;not null" json:"task_id"`                                              // 任务id
	Status                  int32                 `gorm:"column:status;not null;comment:逻辑视图状态 扫描结果 0：无变化、1：新增、2：删除、3：变更" json:"status"`       // 逻辑视图状态\扫描结果 0：无变化、1：新增、2：删除、3：变更
	PublishAt               *time.Time            `gorm:"column:publish_at;comment:发布时间" json:"publish_at"`                                    // 发布时间
	EditStatus              int32                 `gorm:"column:edit_status;not null;comment:内容状态 1：草稿(新增)、2：最新(完善字段业务名称)" json:"edit_status"` // 内容状态 1：草稿(新增)、2：最新(完善字段业务名称)
	OwnerId                 sql.NullString        `gorm:"column:owner_id;comment:数据Ownerid" json:"owner_id"`                                   // 数据Ownerid
	SubjectId               sql.NullString        `gorm:"column:subject_id;comment:主题域id" json:"subject_id"`                                   // 主题域id
	DepartmentId            sql.NullString        `gorm:"column:department_id;comment:所属部门id" json:"department_id"`                            // 所属部门id
	InfoSystemID            string                `gorm:"column:info_system_id;comment:关联信息系统ID" json:"info_system_id"`                        // 关联信息系统ID
	SceneAnalysisId         string                `gorm:"column:scene_analysis_id;comment:场景分析画布id" json:"scene_analysis_id"`                  // 场景分析画布id
	Description             sql.NullString        `gorm:"column:description;comment:逻辑视图描述" json:"description"`                                // 逻辑视图描述
	Comment                 sql.NullString        `gorm:"column:comment;comment:逻辑视图备注" json:"comment"`                                        // 逻辑视图备注
	CreatedAt               time.Time             `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                           // 创建时间
	CreatedByUID            string                `gorm:"column:created_by_uid;not null;comment:创建人id" json:"created_by_uid"`                  // 创建人id
	UpdatedAt               time.Time             `gorm:"column:updated_at;not null;autoUpdateTime;comment:编辑时间" json:"updated_at"`            // 编辑时间
	UpdatedByUID            string                `gorm:"column:updated_by_uid;not null;comment:编辑人id" json:"updated_by_uid"`                  // 编辑人id
	DeletedAt               soft_delete.DeletedAt `gorm:"column:deleted_at;not null;softDelete:milli" json:"deleted_at"`
	ExploreJobId            *string               `gorm:"column:explore_job_id" json:"explore_job_id"`           // 探查作业ID
	ExploreJobVer           *int                  `gorm:"column:explore_job_version" json:"explore_job_version"` // 探查作业版本
	ExploreTimestampID      *string               `gorm:"column:explore_timestamp_id" json:"explore_timestamp_id"`
	ExploreTimestampVersion *int32                `gorm:"column:explore_timestamp_version" json:"explore_timestamp_version"`
	FlowID                  string                `gorm:"column:flow_id;type:varchar(50);not null;comment:审核流程实例id" json:"flow_id"`               // 审核流程实例id
	FlowName                string                `gorm:"column:flow_name;type:varchar(200);not null;comment:审核流程名称" json:"flow_name"`            // 审核流程名称
	FlowNodeID              string                `gorm:"column:flow_node_id;type:varchar(50);not null;comment:当前所处审核流程结点id" json:"flow_node_id"` // 当前所处审核流程结点id
	FlowNodeName            string                `gorm:"column:flow_node_name;type:varchar(200);not null;comment:当前所处审核流程结点名称" json:"flow_node_name"`
	OnlineStatus            string                `gorm:"column:online_status;type:varchar(20);not null;default:notline;comment:上线状态 " json:"status"`                                                                        // 上线状态 未上线 notline、已上线 online、已下线offline、上线审核中up-auditing、下线审核中down-auditing、上线审核未通过up-reject
	AuditType               string                `gorm:"column:audit_type;type:varchar(50);not null;default:unpublished;comment:审核类型 unpublished 未发布 af-data-view-online 上线审核 af-data-view-offline 下线审核" json:"audit_type"` // 审核类型 unpublished 未发布 af-data-view-online 上线审核 af-data-view-offline  下线审核
	AuditStatus             string                `gorm:"column:audit_status;type:varchar(20);not null;default:unpublished;comment:审核状态 unpublished 未发布 auditing 审核中 pass 通过 reject 驳回" json:"audit_status"`                 // 审核状态 unpublished 未发布 auditing 审核中 pass 通过 reject 驳回
	ApplyID                 uint64                `gorm:"column:apply_id;not null;comment:审核申请id" json:"apply_id"`
	ProcDefKey              string                `gorm:"column:proc_def_key;type:varchar(128);not null;comment:审核流程key" json:"proc_def_key"` // 审核流程key
	AuditAdvice             string                `gorm:"column:audit_advice;type:text;not null;comment:审核意见，仅驳回时有用" json:"audit_advice"`
	OnlineTime              *time.Time            `gorm:"column:online_time;type:datetime;comment:上线时间" json:"online_time"`    // 上线时间
	FilterRule              string                `gorm:"column:filter_rule;type:text;comment:数据过滤规则sql" json:"filter_rule"`   // 数据过滤规则sql
	ExcelFileName           string                `gorm:"column:excel_file_name;comment:excel文件名" json:"excel_file_name"`      // excel文件名
	ExcelSheet              string                `gorm:"column:excel_sheet;comment:sheet页,逗号分隔" json:"excel_sheet"`           // sheet页,逗号分隔
	StartCell               string                `gorm:"column:start_cell;comment:sheet页,逗号分隔" json:"start_cell"`             // 起始单元格
	EndCell                 string                `gorm:"column:end_cell;comment:结束单元格" json:"end_cell"`                       // 结束单元格
	HasHeaders              bool                  `gorm:"column:has_headers;comment:结束单元格" json:"has_headers"`                 // 是否首行作为列名
	SheetAsNewColumn        bool                  `gorm:"column:sheet_as_new_column;comment:结束单元格" json:"sheet_as_new_column"` // 是否将sheet作为新列
	SourceSign              sql.NullInt32         `gorm:"column:source_sign;comment:来源标识" json:"source_sign"`                  // 来源标识
	MdlID                   string                `gorm:"column:mdl_id;comment:统一视图id" json:"mdl_id"`                          // 统一视图id
	UpdateCycle             int32                 `gorm:"column:update_cycle;comment:更新周期" json:"update_cycle"`                // 更新周期
	SharedType              int32                 `gorm:"column:shared_type;comment:共享属性" json:"shared_type"`                  // 共享属性
	OpenType                int32                 `gorm:"column:open_type;comment:开放属性" json:"open_type"`                      // 开放属性
}

// TableName FormView's table name
func (*FormView) TableName() string {
	return TableNameFormView
}

func (d *FormView) BeforeCreate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	var err error
	if d.FormViewID == 0 {
		d.FormViewID, err = utilities.GetUniqueID()
	}
	if len(d.ID) == 0 {
		d.ID = uuid.NewString()
	}
	if d.CreatedAt.IsZero() {
		d.CreatedAt = time.Now()
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return err
}

func (d *FormView) BeforeUpdate(_ *gorm.DB) error {
	if d == nil {
		return nil
	}
	if d.UpdatedAt.IsZero() {
		d.UpdatedAt = time.Now()
	}
	return nil
}

func (d *FormView) UniqueKey() string {
	return "id"
}
