// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/callbacks"
	impl38 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/configuration_center/impl"
	impl46 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/classification_rule/impl"
	impl45 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/classification_rule_algorithm_relation/impl"
	impl14 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/data_classify_attribute_blacklist/impl"
	impl28 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/data_preview_config/impl"
	impl32 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/data_privacy_policy/impl"
	impl33 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/data_privacy_policy_field/impl"
	impl48 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/data_set/impl"
	impl13 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/datasource/impl"
	impl37 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/department_explore_report/impl"
	impl30 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/desensitization_rule/impl"
	impl27 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/explore_rule_config/impl"
	impl24 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/explore_task/impl"
	impl9 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/form_view/impl"
	impl34 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/form_view_extend/impl"
	impl10 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/form_view_field/impl"
	impl42 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/grade_rule/impl"
	impl47 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/grade_rule_group/impl"
	impl49 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/graph_model/impl"
	impl11 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/logic_view/impl"
	impl44 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/recognition_algorithm/impl"
	impl12 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/scan_record/impl"
	impl21 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/sub_view/impl"
	impl20 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/t_data_download_task/impl"
	impl43 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/template_rule/impl"
	impl25 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/tmp_completion/impl"
	impl23 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/tmp_explore_sub_task/impl"
	impl5 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/user/impl"
	impl29 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/gorm/white_list_policy/impl"
	impl7 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/mq/es/impl"
	impl4 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/mq/kafka/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/redis"
	impl17 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/auth_service/impl"
	impl15 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/configuration_center/impl"
	impl6 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/data-subject/impl"
	impl22 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/data_exploration/impl"
	impl36 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/mdl_data_model/impl"
	impl16 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/metadata/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/oss_gateway"
	impl39 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/scene_analysis/impl"
	impl18 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/standardization_backend/impl"
	impl8 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/rest/virtualization_engine/impl"
	impl26 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/sailor_service/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driven/workflow"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver"
	v1_16 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/classification_rule/v1"
	v1_6 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/data_lineage/v1"
	v1_12 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/data_privacy_policy/v1"
	v1_22 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/data_set/v1"
	v1_25 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/explore_rule/v1"
	v1_10 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/explore_task/v1"
	v1_4 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/form_view/v1"
	v1_18 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/grade_rule/v1"
	v1_20 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/grade_rule_group/v1"
	v1_23 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/graph_model/v1"
	v1_7 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/logic_view/v1"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/middleware"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/datasource"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/explore"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/explore_task"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/form_view"
	kafka2 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/kafka"
	"github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/mq/standardization"
	v1_14 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/recognition_algorithm/v1"
	v1_8 "github.com/kweaver-ai/dsg/services/apps/data-view/adapter/driver/sub_view/v1"
	"github.com/kweaver-ai/dsg/services/apps/data-view/common/app"
	"github.com/kweaver-ai/dsg/services/apps/data-view/common/initialization"
	v1_15 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/classification_rule/v1"
	"github.com/kweaver-ai/dsg/services/apps/data-view/domain/common"
	"github.com/kweaver-ai/dsg/services/apps/data-view/domain/data_lineage/processor"
	v1_5 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/data_lineage/v1"
	v1_11 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/data_privacy_policy/v1"
	v1_21 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/data_set/v1"
	v1_24 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/explore_rule/v1"
	v1_9 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/explore_task/v1"
	v1_3 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/form_view/v1"
	v1_17 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/grade_rule/v1"
	v1_19 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/grade_rule_group/v1"
	impl61 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/graph_model/impl"
	impl40 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/logic_view/impl"
	v1_13 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/recognition_algorithm/v1"
	impl41 "github.com/kweaver-ai/dsg/services/apps/data-view/domain/sub_view/impl"
	"github.com/kweaver-ai/dsg/services/apps/data-view/infrastructure/cache"
	"github.com/kweaver-ai/dsg/services/apps/data-view/infrastructure/config"
	"github.com/kweaver-ai/dsg/services/apps/data-view/infrastructure/db"
	"github.com/kweaver-ai/dsg/services/apps/data-view/infrastructure/mq/kafka"
	v1_2 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	"github.com/kweaver-ai/idrm-go-common/rest"
	impl59 "github.com/kweaver-ai/idrm-go-common/rest/af_sailor/impl"
	impl60 "github.com/kweaver-ai/idrm-go-common/rest/af_sailor_service/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl3 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl31 "github.com/kweaver-ai/idrm-go-common/rest/business_grooming/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl51 "github.com/kweaver-ai/idrm-go-common/rest/data_application_service/impl"
	impl35 "github.com/kweaver-ai/idrm-go-common/rest/data_catalog/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/data_subject/data_subject_impl"
	impl52 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	impl53 "github.com/kweaver-ai/idrm-go-common/rest/indicator_management/impl"
	impl58 "github.com/kweaver-ai/idrm-go-common/rest/label/impl"
	impl54 "github.com/kweaver-ai/idrm-go-common/rest/metadata_manage/impl"
	impl55 "github.com/kweaver-ai/idrm-go-common/rest/scene_analysis/impl"
	impl19 "github.com/kweaver-ai/idrm-go-common/rest/standardization/impl"
	impl50 "github.com/kweaver-ai/idrm-go-common/rest/task_center/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/user_management"
	impl57 "github.com/kweaver-ai/idrm-go-common/rest/virtual_engine/impl"
	impl56 "github.com/kweaver-ai/idrm-go-common/rest/workflow/impl"
	"github.com/kweaver-ai/idrm-go-frame/core/telemetry/trace"
)

// Injectors from wire.go:

func InitApp(conf *config.Bootstrap) (*app.AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := impl.NewHydraByService(client)
	drivenUserMgnt := user_management.NewUserMgntByService(client)
	driven := impl2.NewConfigurationCenterDrivenByService(client)
	logger, cleanup, err := initialization.InitAuditLog(conf)
	if err != nil {
		return nil, nil, err
	}
	authorizationDriven := impl3.NewDriven(client)
	authServiceInternalV1Interface, err := v1.NewInternalForBase(client)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middlewareMiddleware := v1_2.NewMiddleware(hydra, drivenUserMgnt, driven, logger, authorizationDriven, authServiceInternalV1Interface)
	gormDB, cleanup2, err := db.NewDB(conf)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kafkaPub, err := impl4.NewKafkaProducer(conf)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepo := impl5.NewUserRepo(gormDB, drivenUserMgnt)
	drivenDataSubject := impl6.NewDataSubject(conf, client)
	esRepo := impl7.NewESRepo(driven, kafkaPub, userRepo, drivenDataSubject)
	drivenVirtualizationEngine := impl8.NewVirtualizationEngine(conf)
	formViewRepo := impl9.NewFormViewRepo(gormDB, esRepo, drivenVirtualizationEngine)
	workflowInterface, err := workflow.NewWorkflow(conf, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	formViewFieldRepo := impl10.NewFormViewFieldRepo(gormDB)
	logicViewRepo := impl11.NewLogicViewRepo(gormDB, workflowInterface, driven, formViewFieldRepo, esRepo)
	scanRecordRepo := impl12.NewScanRecordRepo(gormDB)
	datasourceRepo := impl13.NewDatasourceRepo(gormDB)
	dataClassifyAttrBlacklistRepo := impl14.NewDataClassifyAttrBlacklistRepo(gormDB)
	configurationCenterDrivenNG := impl15.NewConfigurationCenterDrivenNG(conf, client)
	drivenMetadata := impl16.NewMetadata(conf, client)
	drivenAuthService := impl17.NewAuthService(conf, client)
	data_subjectDriven := data_subject_impl.NewDataViewDriven(client)
	redis := cache.NewRedis()
	drivenStandardizationRepo := impl18.NewStandardizationBackend(conf, client)
	standardizationDriven := impl19.NewDriven(client)
	cephClient, err := oss_gateway.NewCephClient(client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redissonInterface := redisson.NewRedisson(redis)
	tDataDownloadTaskRepo := impl20.NewTDataDownloadTaskRepo(gormDB)
	subViewRepo := impl21.NewSubViewRepo(gormDB)
	drivenDataExploration := impl22.NewDataExploration(conf, client)
	tmpExploreSubTaskRepo := impl23.NewExploreTaskRepo(gormDB)
	exploreTaskRepo := impl24.NewExploreTaskRepo(gormDB)
	syncProducer, err := kafka.NewSyncProducer(conf)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kafkaProducer := kafka2.NewKafkaProducer(syncProducer)
	tmpCompletionRepo := impl25.NewTmpCompletionRepo(gormDB)
	graphSearch := impl26.NewSailorServiceCall(client, conf)
	exploreRuleConfigRepo := impl27.NewExploreRuleConfigRepo(gormDB)
	commonUseCase := common.NewCommonUseCase(formViewFieldRepo, standardizationDriven, drivenUserMgnt, drivenDataSubject, driven)
	dataPreviewConfigRepo := impl28.NewDataPreviewConfigRepo(gormDB)
	whiteListPolicyRepo := impl29.NewWhiteListPolicyRepo(gormDB)
	desensitizationRuleRepo := impl30.NewDesensitizationRuleRepo(gormDB)
	business_groomingDriven := impl31.NewDriven(client)
	dataPrivacyPolicyRepo := impl32.NewDataPrivacyPolicyRepo(gormDB)
	dataPrivacyPolicyFieldRepo := impl33.NewDataPrivacyPolicyFieldRepo(gormDB)
	formViewExtendRepo := impl34.NewFormViewExtendRepo(gormDB)
	labelService := middleware.NewConfigurationCenterLabelService(conf, client)
	data_catalogDriven := impl35.NewDrivenImpl(client)
	drivenMdlDataModel := impl36.NewMdlDataModel(conf, client)
	departmentExploreReportRepo := impl37.NewDepartmentExploreReportRepo(gormDB)
	formViewUseCase := v1_3.NewFormViewUseCase(formViewRepo, logicViewRepo, userRepo, formViewFieldRepo, scanRecordRepo, datasourceRepo, dataClassifyAttrBlacklistRepo, drivenUserMgnt, driven, configurationCenterDrivenNG, drivenVirtualizationEngine, drivenMetadata, drivenAuthService, kafkaPub, data_subjectDriven, drivenDataSubject, redis, drivenStandardizationRepo, standardizationDriven, cephClient, redissonInterface, tDataDownloadTaskRepo, subViewRepo, drivenDataExploration, tmpExploreSubTaskRepo, exploreTaskRepo, kafkaProducer, workflowInterface, esRepo, tmpCompletionRepo, graphSearch, exploreRuleConfigRepo, commonUseCase, dataPreviewConfigRepo, whiteListPolicyRepo, desensitizationRuleRepo, business_groomingDriven, dataPrivacyPolicyRepo, dataPrivacyPolicyFieldRepo, formViewExtendRepo, labelService, data_catalogDriven, authServiceInternalV1Interface, authorizationDriven, drivenMdlDataModel, departmentExploreReportRepo)
	formViewService := v1_4.NewFormViewService(formViewUseCase)
	objectSearch := impl38.NewConfigurationCenterCall(client, conf)
	sceneAnalysisDriven := impl39.NewSceneAnalysisDriven(conf, client)
	formViewInfoFetcher := processor.NewFormViewInfoFetcher(driven, formViewRepo, gormDB, userRepo, datasourceRepo, sceneAnalysisDriven)
	useCase := v1_5.NewViewLineageUseCase(formViewRepo, conf, formViewFieldRepo, datasourceRepo, graphSearch, objectSearch, redis, formViewInfoFetcher)
	service := v1_6.NewFormViewService(useCase)
	logicViewUseCase := impl40.NewLogicViewUseCase(conf, formViewRepo, formViewUseCase, logicViewRepo, userRepo, formViewFieldRepo, datasourceRepo, driven, configurationCenterDrivenNG, drivenVirtualizationEngine, drivenMetadata, drivenAuthService, drivenDataSubject, sceneAnalysisDriven, graphSearch, kafkaPub, workflowInterface, esRepo, redis, redissonInterface, commonUseCase, exploreRuleConfigRepo, subViewRepo, drivenMdlDataModel)
	logicViewService := v1_7.NewLogicViewService(logicViewUseCase)
	subViewUseCase := impl41.NewSubViewUseCase(datasourceRepo, logicViewRepo, formViewFieldRepo, subViewRepo, drivenAuthService, kafkaPub, authServiceInternalV1Interface)
	subViewService := v1_8.NewSubViewService(subViewUseCase)
	gradeRuleRepo := impl42.NewGradeRuleRepo(gormDB)
	templateRuleRepo := impl43.NewTemplateRuleRepo(gormDB)
	exploreTaskUseCase := v1_9.NewExploreTaskUseCase(exploreTaskRepo, formViewRepo, formViewFieldRepo, userRepo, datasourceRepo, tmpExploreSubTaskRepo, dataClassifyAttrBlacklistRepo, drivenDataExploration, kafkaProducer, graphSearch, redissonInterface, drivenStandardizationRepo, exploreRuleConfigRepo, configurationCenterDrivenNG, drivenDataSubject, gradeRuleRepo, driven, objectSearch, templateRuleRepo)
	exploreTaskService := v1_10.NewExploreTaskService(exploreTaskUseCase)
	dataPrivacyPolicyUseCase := v1_11.NewDataPrivacyPolicyUseCase(dataPrivacyPolicyRepo, dataPrivacyPolicyFieldRepo, driven, drivenDataSubject, userRepo, formViewRepo, formViewFieldRepo, desensitizationRuleRepo, drivenVirtualizationEngine, datasourceRepo)
	dataPrivacyPolicyService := v1_12.NewDataPrivacyPolicyService(dataPrivacyPolicyUseCase)
	recognitionAlgorithmRepo := impl44.NewRecognitionAlgorithmRepo(gormDB)
	classificationRuleAlgorithmRelationRepo := impl45.NewClassificationRuleAlgorithmRelationRepo(gormDB)
	classificationRuleRepo := impl46.NewClassificationRuleRepo(gormDB)
	recognitionAlgorithmUseCase := v1_13.NewRecognitionAlgorithmUseCase(recognitionAlgorithmRepo, userRepo, classificationRuleAlgorithmRelationRepo, classificationRuleRepo, drivenDataSubject)
	recognitionAlgorithmService := v1_14.NewRecognitionAlgorithmService(recognitionAlgorithmUseCase)
	classificationRuleUseCase := v1_15.NewClassificationRuleUseCase(classificationRuleRepo, userRepo, classificationRuleAlgorithmRelationRepo, recognitionAlgorithmRepo, drivenDataSubject, formViewFieldRepo)
	classificationRuleService := v1_16.NewClassificationRuleService(classificationRuleUseCase)
	gradeRuleGroupRepo := impl47.NewGradeRuleGroupRepo(gormDB)
	gradeRuleUseCase := v1_17.NewGradeRuleUseCase(gradeRuleRepo, gradeRuleGroupRepo, userRepo, drivenDataSubject, driven)
	gradeRuleService := v1_18.NewGradeRuleService(gradeRuleUseCase)
	gradeRuleGroupUseCase := v1_19.NewGradeRuleGroupUseCase(gradeRuleGroupRepo, gradeRuleRepo)
	gradeRuleGroupService := v1_20.NewGradeRuleGroupService(gradeRuleGroupUseCase)
	dataSetRepo := impl48.NewDataSetRepo(gormDB)
	dataSetUseCase := v1_21.NewDataSetUseCase(dataSetRepo, formViewUseCase, formViewRepo, gormDB, drivenDataSubject, driven)
	dataSetService := v1_22.NewDataSetService(dataSetUseCase)
	repo := impl49.NewRepo(gormDB)
	task_centerDriven := impl50.NewDriven(client)
	data_application_serviceDriven := impl51.NewDrivenImpl(client)
	data_viewDriven := impl52.NewDataViewDriven(client)
	indicator_managementDriven := impl53.NewDrivenImpl(client)
	metadata_manageDriven := impl54.NewDrivenImpl(client)
	scene_analysisSceneAnalysisDriven := impl55.NewSceneAnalysisDrivenByServiceName(client)
	workflowDriven := impl56.NewWorkflowDriven(client)
	virtual_engineDriven := impl57.NewDrivenImpl(client)
	labelDriven := impl58.NewBigDataDriven(client)
	af_sailorDriven := impl59.NewSailorDriven(client)
	af_sailor_serviceDriven := impl60.NewSailorDriven(client)
	restService := &rest.Service{
		BusinessGrooming:       business_groomingDriven,
		TaskCenter:             task_centerDriven,
		ConfigurationCenter:    driven,
		DataApplicationService: data_application_serviceDriven,
		DataCatalog:            data_catalogDriven,
		DataSubject:            data_subjectDriven,
		DataView:               data_viewDriven,
		IndicatorManagement:    indicator_managementDriven,
		MetadataManagement:     metadata_manageDriven,
		SceneAnalysis:          scene_analysisSceneAnalysisDriven,
		Standardization:        standardizationDriven,
		Workflow:               workflowDriven,
		VirtualEngine:          virtual_engineDriven,
		Hydra:                  hydra,
		BasicBigDataService:    labelDriven,
		Sail:                   af_sailorDriven,
		SailService:            af_sailor_serviceDriven,
		UserManagement:         drivenUserMgnt,
		Authorization:          authorizationDriven,
	}
	graph_modelUseCase := impl61.NewUseCase(repo, restService, formViewFieldRepo, formViewRepo, driven)
	v1Service := v1_23.NewGraphModel(graph_modelUseCase)
	exploreRuleUseCase := v1_24.NewExploreRuleUseCase(formViewRepo, formViewFieldRepo, exploreRuleConfigRepo, templateRuleRepo)
	exploreRuleService := v1_25.NewExploreRuleService(exploreRuleUseCase)
	iRouter := driver.NewRouter(middlewareMiddleware, formViewService, service, logicViewService, subViewService, exploreTaskService, dataPrivacyPolicyService, recognitionAlgorithmService, classificationRuleService, gradeRuleService, gradeRuleGroupService, dataSetService, v1Service, exploreRuleService)
	server := driver.NewHttpEngine(conf, iRouter)
	v1Server := v1_3.NewServer(tmpCompletionRepo, conf)
	v := app.ToTransportServer(server, v1Server)
	idrm_go_frameApp := app.NewApp(conf, server, v)
	consumerGroupFactory := kafka.NewConsumerGroupProduct(conf)
	mqClient, err := kafka2.NewConsumerClient(consumerGroupFactory)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataSourceConsumer := datasource.NewDataSourceConsumer(datasourceRepo, formViewRepo, formViewUseCase, scanRecordRepo)
	dataExplorationHandler := data_explore.NewDataExplorationHandler(formViewUseCase)
	exploreTaskHandler := explore_task.NewExploreTaskHandler(exploreTaskUseCase)
	formViewHandler := form_view.NewFormViewHandler(formViewUseCase, formViewRepo)
	handler := standardization.NewStandardizationHandler(logicViewUseCase)
	mqHandler := mq.NewMQHandler(mqClient, dataSourceConsumer, dataExplorationHandler, exploreTaskHandler, formViewHandler, handler)
	entityChangeTransport := callbacks.NewEntityChangeTransport(kafkaPub)
	dataLineageTransport := callbacks.NewDataLineageTransport(metadata_manageDriven, formViewInfoFetcher)
	transports := callbacks.NewTransport(gormDB, entityChangeTransport, dataLineageTransport)
	wfStarter := workflow.NewWFStarter(workflowInterface)
	appRunner := app.NewAppRunner(idrm_go_frameApp, mqHandler, transports, wfStarter)
	return appRunner, func() {
		cleanup2()
		cleanup()
	}, nil
}
