namespace: anyshare

labels:
  deployment:
    name: data-semantic-deployment
  pod:
    app: data-semantic-pod
  service:
    app: data-semantic-service
  api:
    deployment:
      app: data-semantic-api
      component: api
    pod:
      app: data-semantic-api
      component: api
    service:
      app: data-semantic-api
  consumer:
    deployment:
      app: data-semantic-consumer
      component: consumer
    pod:
      app: data-semantic-consumer
      component: consumer

name: data-semantic-deployment

image:
  registry: acr.xxx.cn
  repository: af/data-semantic
  tag: "1.0.0-develop"
  pullPolicy: IfNotPresent

nodeSelector: []

service:
  name: data-semantic
  type: ClusterIP
  port: 8888
  telemetry:
    log:
      enabled: false
      endpoint: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/job-log/events
      level: info
    trace:
      enabled: false
      endpoint: http://feed-ingester-service:13031/api/feed_ingester/v1/jobs/job-trace/events

ports:
  name: server-port
  containerPort: 8888

depServices:
  class-443:
    ingressClass: class-443
  rds:
    type: mariadb
    host: mariadb-mariadb-master.resource.svc.cluster.local
    port: 3330
    user: anyshare
    password: xxx
    database: af_main
  hydra:
    administrativeHost: hydra-admin
    administrativePort: 4445
  user-management:
    privateHost: user-management-private
    privatePort: 30980
  af-sailor-service:
    protocol: http
    host: af-sailor-agent
    port: 9595
  mq:
    mqType: kafka
    mqHost: kafka-headless.resource
    mqPort: 9097
    auth:
      username: kafkaclient
      password: xxx
  redis:
    host: proton-redis-proton-redis-sentinel.resource.svc.cluster.local
    port: 26379
    database: 0
    password: xxx

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

consumer:
  enabled: true
  name: data-semantic-consumer
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
